//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYMVC.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;

	[System.ComponentModel.DataAnnotations.Schema.Table("AccountTransaction")]
    public partial class AccountTransaction
	{
        public int Id { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Cost { get; set; }
		[DisplayName("From Account")]
		public Nullable<int> FromAccount { get; set; }
		[DisplayName("From Investment")]
        public Nullable<int> FromInvestment { get; set; }
		[DisplayName("To Account")]
        public Nullable<int> ToAccount { get; set; }
		[DisplayName("To Investment")]
        public Nullable<int> ToInvestment { get; set; }
		public bool Deleted { get; set; }
        public Nullable<int> CreateUser { get; set; }
		[DisplayName("Date")]
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }

		public string TypeName;
		public string FromAccountName;
		public string FromInvestmentName;
		public string ToAccountName;
		public string ToInvestmentName;
	}
}
