//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYMVC.Models
{
    using System;
    using System.Collections.Generic;
    
	[System.ComponentModel.DataAnnotations.Schema.Table("AccountValueHistory")]
    public partial class AccountValueHistory
	{
        public int Id { get; set; }
        public Nullable<int> AccountId { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
        public bool Deleted { get; set; }
		public Nullable<int> CreateUser { get; set; }
		public Nullable<System.DateTime> CreateDate { get; set; }
		public Nullable<int> UpdateUser { get; set; }
		public Nullable<System.DateTime> UpdateDate { get; set; }
	}
}
