//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SYMVC.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel;

	[System.ComponentModel.DataAnnotations.Schema.Table("Investment")]
	public partial class Investment
    {		
        public int Id { get; set; }
        public Nullable<int> Type { get; set; }
		[DisplayName("Investment")]
        public string Title { get; set; }
        public string Description { get; set; }
		[DisplayName("Interest Rate")]
        public Nullable<decimal> IRR { get; set; }
		[DisplayName("Inception Date")]
        public Nullable<System.DateTime> InceptionDate { get; set; }
		[DisplayName("Lock Period [Days]")]
        public Nullable<int> LockPeriodDays { get; set; }
        public Nullable<bool> Closed { get; set; }
        public Nullable<int> Status { get; set; }
		public bool Deleted { get; set; }
        public Nullable<int> CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }    
    }
}
